### ISSUE TITLE
New DrBork Multiboard

### ISSUE THREAD

**Issue by seeker7r4c3r** [SkeletonMan03/FZEasyMarauderFlash#14]
The new DrBork Multiboard uses an ESP32S3 chip, but shows with a new HWID in device manager. HWID is '0483'. By adding this to the 'vids' list, I was able to test the flasher and marauder on this board.

**Comment by SkeletonMan03** [comment]
Good to know. Could you fork the repo, add that change, and make a PR that I can merge?

**Comment by seeker7r4c3r** [comment]
Sure thing

**Comment by seeker7r4c3r** [comment]
PR sent

**Comment by SkeletonMan03** [comment]
I have merged it. Thank you, I really appreciate the help

**Comment by seeker7r4c3r** [comment]
Thanks for the quick responses
