### ISSUE TITLE
i have no clue whats goin on

### ISSUE THREAD

**Issue by Pornhubber** [SkeletonMan03/FZEasyMarauderFlash#19]
C:\Users\minec\OneDrive\Desktop\FZEasyMarauderFlash-main>python EasyInstall.py
Traceback (most recent call last):
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\minec\OneDrive\Desktop\FZEasyMarauderFlash-main\EasyInstall.py", line 4, in <module>
    from git import Repo
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by SkeletonMan03** [comment]
t tells you your Git install is messed up, or you just don't even have it... Install or reinstall Git for Windows
