### ISSUE TITLE
Sniffraw empty

### ISSUE THREAD

**Issue by itsmesikander** [SkeletonMan03/FZEasyMarauderFlash#30]
When I am downloading sniffraw file to pc and dropping into wireshark. Then nothing happens its completely empty. Is there something I am missing.
Thanks

**Comment by SkeletonMan03** [comment]
Check the Marauder Wiki. I'm not sure why that wouldn't work, but is not related to this tool, but Marauder itself

**Comment by chrisbward** [comment]
Also having this issue when using this installer today.

Does this discussion help for a fix? 
Does this firmware installer drop the correct file in the flash process?

https://www.reddit.com/r/flipperzero/comments/13awbol/the_solution_to_the_empty_pcap_files_credit_and/

**Comment by chrisbward** [comment]
Quick question - what's a known-working custom firmware to put on the flipper for this script?
