### ISSUE TITLE
Cant install anything on mac

### ISSUE THREAD

**Issue by dxvdmj** [SkeletonMan03/FZEasyMarauderFlash#34]
I copied the scripts to run in terminal on a mac and it is detecting the wifi board in the port but its reading an error of cant install, any help would be very appreciated!

Error in question -

ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/__init__.py)

**Comment by SkeletonMan03** [comment]
That error, especially by itself, doesn't really tell me anything useful. It does tell me however that you're using Python 3.8 while the latest is 3.11.3 and you should upgrade.
