### ISSUE TITLE
Raw sniff file with 0kb

### ISSUE THREAD

**Issue by zunderStake** [SkeletonMan03/FZEasyMarauderFlash#35]
I have flashed my ESP32-WROOM and when performing a sniff in raw mode the file generated in my SD has a weight of 0Kb.

**Comment by SkeletonMan03** [comment]
This is not an issue with the tool as it pulls resources from the Marauder Github. The ESP32-WROOM also does not support that feature.

**Comment by chrisbward** [comment]
https://github.com/SkeletonMan03/FZEasyMarauderFlash/issues/30
