### ISSUE TITLE
Cant install easyinstall.py on window

### ISSUE THREAD

**Issue by redgoat444** [SkeletonMan03/FZEasyMarauderFlash#37]
python3 EasyInstall.py
#then i got this error.
Traceback (most recent call last):
  File "EasyInstall.py", line 4, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'

**Comment by SkeletonMan03** [comment]
You didn't follow the instructions. You're getting that because you didn't install Git For Windows. And did you even do step 0?
