### ISSUE TITLE
No module named 'git'

### ISSUE THREAD

**Issue by Miahporter** [SkeletonMan03/FZEasyMarauderFlash#38]
Running Mac OS Ventura 13.1. When i run "pip3 install -r requirements.txt" in poweshell everything runs fine. once i add "python3 EasyInstall.py" i get error "line 4, in <module> from git import Repo ModuleNotFoundError: No module named 'git'"

**Comment by SkeletonMan03** [comment]
You didn't install Git first

**Comment by Cruxz21** [comment]
so i have downloaded everything is running fine yet i still get the same error do i have to update or do something in git to get it running fine
