### ISSUE TITLE
Can't flash s3 firmware

### ISSUE THREAD

**Issue by Havivw** [SkeletonMan03/FZEasyMarauderFlash#40]
Make sure your ESP32 or WiFi devboard is plugged in!
Checking for prerequisites...
The extra ESP32 bins folder does not exist!
That's okay, downloading them now...
Checking for Marauder releases
Marauder releases folder does not exist, but that's okay, downloading them now...
ESP32 Marauder firmware exists at ESP32Marauder/releases/esp32_marauder_v0_10_6_20230606_flipper.bin
ESP32 Marauder firmware exists at ESP32Marauder/releases/esp32_marauder_v0_10_6_20230606_flipper_sd_serial.bin
mutliboards3 bin does not exist!
Old Hardware bin exists at ESP32Marauder/releases/esp32_marauder_v0_10_6_20230606_old_hardware.bin
Mini bin exists at ESP32Marauder/releases/esp32_marauder_v0_10_6_20230606_mini.bin

//======================================================\\
|| Options:						||
|| 1) Flash Marauder on WiFi Devboard or ESP32-S2	||
|| 2) Flash SD Serial Marauder on Devboard or ESP32-S2	||
|| 3) Save Flipper Blackmagic WiFi settings		||
|| 4) Flash Flipper Blackmagic				||
|| 5) Flash Marauder on ESP32-WROOM			||
|| 6) Flash Marauder on ESP32 Wemos D1 Mini		||
|| 7) Flash Marauder on ESP32-S3			||
|| 8) Update all files					||
|| 9) Exit						||
\\======================================================//

Please enter the number of your choice: 7
You have chosen to flash Marauder onto an ESP32-S3
Checking for serial port...
You are most likely using an DrB0rk S3 Multiboard
Erasing firmware...
esptool.py v4.5.1
Serial port /dev/cu.usbmodemflip_Kilg_re1
Connecting...
Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: ...........
Uploading stub...
Running stub...
Stub running...
Erasing region (may be slow depending on size)...
Erase completed successfully in 0.3 seconds.
Staying in bootloader.
esp32s3 was successfully erased!
Waiting 5 seconds...
Flashing ESP32 Marauder Firmware onto ESP32-S3...
name 'esp32s3fw' is not defined
Waiting 5 seconds and trying again...
Flashing ESP32 Marauder Firmware onto ESP32-S3...
name 'esp32s3fw' is not defined
Waiting 5 seconds and trying again...
Flashing ESP32 Marauder Firmware onto ESP32-S3...
name 'esp32s3fw' is not defined
Could not flash Marauder firmware on ESP32-S3

**Comment by SkeletonMan03** [comment]
> you had a typo fix and send a PR

Thanks for the PR. I however, did not have a typo. The release for that bit *was* "mutliboard" instead of "multiboard" for some reason until the latest release
