### ISSUE TITLE
Windows silabs usb to uart bridge vcp link no longer has a download

### ISSUE THREAD

**Issue by AlphaHasher** [SkeletonMan03/FZEasyMarauderFlash#5]
In the windows section there is a link listed for the required drivers
This is the link listed
https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

It no longer works and the drivers have been removed from the site it seems

**Comment by SkeletonMan03** [comment]
The link works and the drivers are there... I assume it's blocked on your network for some reason
