### ISSUE TITLE
No Wifi(Marauder) item in the menu

### ISSUE THREAD

**Issue by Drjacky** [SkeletonMan03/FZEasyMarauderFlash#52]
I used number 1 and it flashed it into FlipperZero successfully but I still don't see the Wifi(Marauder):
Mine:
<img width="243" alt="Screenshot 2023-10-05 at 17 02 16" src="https://github.com/SkeletonMan03/FZEasyMarauderFlash/assets/2296754/4ecf4a15-c39a-4978-b35f-3e9652d841f3">

Demo:
<img width="546" alt="Screenshot 2023-10-05 at 17 01 32" src="https://github.com/SkeletonMan03/FZEasyMarauderFlash/assets/2296754/9f97f26c-3c7d-4e51-8db4-86609d60b5ec">

**Comment by SkeletonMan03** [comment]
..........

**Comment by SkeletonMan03** [comment]
This does not install the Marauder app for you on your Flipper. This installs the ESP32 FW

**Comment by Drjacky** [comment]
My bad. I meant WiFi Devboard for Flipper Zero
