### ISSUE TITLE
Issue with  2) Flash SD Serial Marauder on WiFi Devboard or ESP32-S2

### ISSUE THREAD

**Issue by JayTongue** [SkeletonMan03/FZEasyMarauderFlash#58]
From the flash menu, when I select option2, I get 

`NameError: name 'esp32marauderfwserial' is not defined. Did you mean: 'esp32marauderfw'?`

Is this an issue with the installer script?

**Comment by SkeletonMan03** [comment]
Technically, yes it is now. As of the latest Marauder update that bin no longer exists because of the unified serial update, meaning option 1 would also work for you assuming you're using the latest Marauder Companion FAP. I'll remove that option when I get time tomorrow.

**Comment by SkeletonMan03** [comment]
@JayTongue this has been fixed with the latest update
