### ISSUE TITLE
How to know what Marauder version was installed? 

### ISSUE THREAD

**Issue by LEO2008k** [SkeletonMan03/FZEasyMarauderFlash#59]
Dear developers of that wonderful. script. Would you please explain, or how to confirm of what version of FW of Marauder was installed by your script option 1? I installed that, without errors. But in Flipper menu Apps -> GPIO -> Marauder -> shows "Marauder companion v0.6.6 Press BACK to send stopscan" My expectation, should be latest version [source](https://github.com/justcallmekoko/ESP32Marauder/releases/tag/v0.13.7)?

**Comment by SkeletonMan03** [comment]
The version is in the filename of the bins... Which it shows you after it downloads them. It will always pull the latest

**Comment by LEO2008k** [comment]
Well, I don't know why? And I didn't checked files via md5sum to compare it. So, I'm not sure if that EasyInstall.py script install latest version. I managed to update the firmware via that service https://lab.flipper.net/apps/esp32_wifi_marauder.
THANK YOU
