### ISSUE TITLE
Flash SD Serial Marauder on Devboard or ESP32-S2 missing from menu

### ISSUE THREAD

**Issue by shayaansiddiqui** [SkeletonMan03/FZEasyMarauderFlash#67]
https://youtu.be/subLBPJ3IxU?t=299

Tutorial shows #2 as 'Flash SD Serial Marauder on Devboard or ESP32-S2'
I searched your git history and can't find it. Could you please tell us what option has replaced that older option OR add it back to the menu?

<img width="804" alt="image" src="https://github.com/user-attachments/assets/c1e5aa76-976a-42c5-a44e-599fc7a99c41">

**Comment by SkeletonMan03** [comment]
Per the message you didn't read:
"As of Marauder Update 0.13.7, there is no more serial bin, it is unified, but #
# the latest Marauder Companion App (7.0) is required to use it on your Flipper"
