### ISSUE TITLE
There is no suitable bin file for ESP-S3

### ISSUE THREAD

**Issue by haojiahuo123** [SkeletonMan03/FZEasyMarauderFlash#71]
Mine is ESP32-S3, and the problem as shown in the picture occurs. Is it because my board does not have an SD card inserted? In addition, I ran option 7 and an error occurred. Why is this?
![image](https://github.com/user-attachments/assets/bdeb2e4c-7db1-4fd7-a024-11206ddc127c)

**Comment by urosch** [comment]
specifically "esp32_marauder_v1_0_0_20240626_esp32_multiboardS3.bin" file for version v1_0_0 is missing in releases...

**Comment by SkeletonMan03** [comment]
It's literally not in https://github.com/justcallmekoko/ESP32Marauder/releases/tag/v1.0.0 for some reason... It can't download what doesn't exist...
