### ISSUE TITLE
how can I change the baud rate?

### ISSUE THREAD

**Issue by Mitesz** [SkeletonMan03/FZEasyMarauderFlash#75]
I have an esp32 and a Mac but my esp32 just in 115200 baud rate can write and read. how can I change it?

**Comment by SkeletonMan03** [comment]
@Mitesz https://github.com/SkeletonMan03/FZEasyMarauderFlash/blob/c4bd26c08cb4f2b04571f85f2a2ebb74a7647f4c/EasyInstall.py#L43
